/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkersImport } from './routes/workers'
import { Route as LogsImport } from './routes/logs'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WorkersRoute = WorkersImport.update({
  path: '/workers',
  getParentRoute: () => rootRoute,
} as any)

const LogsRoute = LogsImport.update({
  path: '/logs',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsImport
      parentRoute: typeof rootRoute
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/logs': typeof LogsRoute
  '/workers': typeof WorkersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/logs': typeof LogsRoute
  '/workers': typeof WorkersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/logs': typeof LogsRoute
  '/workers': typeof WorkersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logs' | '/workers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logs' | '/workers'
  id: '__root__' | '/' | '/logs' | '/workers'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LogsRoute: typeof LogsRoute
  WorkersRoute: typeof WorkersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LogsRoute: LogsRoute,
  WorkersRoute: WorkersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/logs",
        "/workers"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/logs": {
      "filePath": "logs.tsx"
    },
    "/workers": {
      "filePath": "workers.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
