/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const WorkersLazyImport = createFileRoute('/workers')()
const LogsLazyImport = createFileRoute('/logs')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WorkersLazyRoute = WorkersLazyImport.update({
  path: '/workers',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/workers.lazy').then((d) => d.Route))

const LogsLazyRoute = LogsLazyImport.update({
  path: '/logs',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logs.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsLazyImport
      parentRoute: typeof rootRoute
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/logs': typeof LogsLazyRoute
  '/workers': typeof WorkersLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/logs': typeof LogsLazyRoute
  '/workers': typeof WorkersLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/logs': typeof LogsLazyRoute
  '/workers': typeof WorkersLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logs' | '/workers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logs' | '/workers'
  id: '__root__' | '/' | '/logs' | '/workers'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LogsLazyRoute: typeof LogsLazyRoute
  WorkersLazyRoute: typeof WorkersLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LogsLazyRoute: LogsLazyRoute,
  WorkersLazyRoute: WorkersLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/logs",
        "/workers"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/logs": {
      "filePath": "logs.lazy.tsx"
    },
    "/workers": {
      "filePath": "workers.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
